### ISSUE TITLE
not possible to push a new record at runtime to the grid ?

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-grids#11]
Hi,

it is not possible to push a new record at runtime to the grid. The grid not show the new record. the source is a simple json array with two fields.

We have tried everything:

-  method addRecord() -> Error "undefined" -> the grid is not undefined
- push new record and than call "databind()" -> the record is not showing.
- push new record and then call "refresh()" -> the record is not showing.
- overwrite the datasource -> the record is not showing.

**is it possible to push a new record to a json datasource at runtime and then we can see the new record?**

Regards
j.nord

**Comment by isuriya-r39** [comment]
We can add the grid record using the addRecord method. Before using the addRecord method  we need to include the EditService in provider section. You can dynamically add record in grid. Here we have added the row in databound event . Please refer the below sample for you reference.

Code example for your reference:

```@Component({
        selector: 'app-container',
        template: `<ej-grid #grid [dataSource]='data' (dataBound)='dataBound($event)' [editSettings]='editSettings'[toolbar]='toolbar' height='315px'>
                    <e-columns>
                        <e-column field='OrderID' headerText='Order ID' textAlign='right' isPrimaryKey='true' width=100></e-column> 
                         . . . . . . 
                    </e-columns>
                    </ej-grid>`
    })
export class AppComponent implements OnInit {

    public data: Object[];
    public editSettings: EditSettingsModel;
     @ViewChild('grid')
    public grid: GridComponent;
    public toolbar: ToolbarItems[];
    public addItem: boolean = true;
   

    dataBound(args: any){
        if (this.addItem) {
            this.addItem = false;
            this.grid.addRecord({"OrderID":1111,"CustomerID":'YYYYY',"ShipCity":'XXXXX'});  
        }
    }
    }
```

Refer documentation about CRUD operation: 

Documentation : http://ej2.syncfusion.com/15.4.23/angular/documentation/grid/edit.html

Sample: http://plnkr.co/edit/jfHbmQMrj97MQtsixuHD?p=preview
