### ISSUE TITLE
Date format changed when the first row contains null value in date column

### ISSUE THREAD

**Issue by LastCodeDE** [syncfusion/ej2-ng-grids#12]
Hi Pavithra,

we had this issue before:
https://github.com/syncfusion/ej2-ng-grids/issues/8

Currently we are using version 16.1.28.

Unfortunately we noted a new failure with the null value in the date column.

If the first row in the column contains a null value in the date column then the value of the next rows will be false displayed (See Attachment).

![firstrowcontainsdate](https://user-images.githubusercontent.com/15675686/37761493-20963cc2-2dba-11e8-86bf-4b8574c70a04.png)
First row contains a normal date.

![firstrownull](https://user-images.githubusercontent.com/15675686/37761504-2627affe-2dba-11e8-8c9c-3a2d12999482.png)
First row contains a null value in date column.

Column format is: 'yMMdd'.

Regards
LastCodeDE

**Comment by bharathm03** [comment]
@LastCodeDE Can you try setting `type` property of that column?

https://ej2.syncfusion.com/16.1.24/angular/documentation/grid/columns.html?lang=typescript#column-type

**Comment by LastCodeDE** [comment]
@bharathm03 It works.

Thank you for the quick answer.

Regards
LastCodeDE
