### ISSUE TITLE
Is there a way to listen on expanding/collapsing details?

### ISSUE THREAD

**Issue by egozavr** [syncfusion/ej2-ng-grids#14]
Hi! Thanks for your product.

I put component to `#detailTemplate`. This component loads some data on component init and I want this data to be refreshed after each detail template expansion. But I didn't find any event triggering on detail template appearance. `detailDataBound` emits only once. So the question is in subj.

**Comment by jvhariharan** [comment]
Hi egozavr,

Thanks for contacting Syncfusion support.

Query : I want this data to be refreshed after each detail template expansion

We have analyzed your requirement and created a sample for your reference. In the below sample, we have bind the click event for the grid and check whether the target element contains e-detailrowexpand (contains when row expand) or e-detailrowcollapse class. You can also achieve your requirement by using the below way. 

Kindly refer to the below code example and sample for more information.

`import { enableRipple,closest } from '@syncfusion/ej2-base';       Grid.Inject(Page, Selection, DetailRow);           let grid: Grid = new Grid({             dataSource: employeeData,             detailTemplate: '#detailtemplate',             width: 'auto',             columns: [                 { field: 'FirstName', headerText: 'First Name', width: 110 },                 { field: 'LastName', headerText: 'Last Name', width: 110 },             ]         });       grid.appendTo('#Grid');       };       grid.element.addEventListener('click', (e) => {           let cell =closest(e.target, 'td');           if (cell.classList.contains('e-detailrowexpand') )   {                  alert("Expand"); // you can   refresh the data here           } else if(cell.classList.contains('e-detailrowcollapse')) {                  alert("Collpase");           }     });
--`

Sample : https://plnkr.co/edit/aZYV2dH7M5OBruZ64oW4?p=preview 

Help documentation : https://ej2.syncfusion.com/documentation/grid/row.html?lang=typescript#detail-template 

Regards,
Hariharan

**Comment by egozavr** [comment]
Ok, thanks for reply
