### ISSUE TITLE
How to add a record at bottom of grid

### ISSUE THREAD

**Issue by yiquanchaoren** [syncfusion/ej2-ng-grids#16]
How to add a record at bottom of grid?

**Comment by ej2gridsamples** [comment]
Hi yiquanchaoren,

Thanks for contacting Syncfusion Support.

We can add the newly added record in the bottom position by setting the ‘args.index’ value in the actionBegin event with ‘save’ requestType. We can also add the adding form in the bottom position by using the ‘actionComplete’ event. We have prepared a simple sample based on your requirement. Please refer to the below code example, Documentation link and sample link.

`@Component({
    selector: 'control-content',
    template: `<ejs-grid #grid [dataSource]='data' [pageSettings]='page' allowPaging=true [editSettings]='editSettings' [toolbar]='toolbar' (actionBegin)='begin($event)' (actionComplete)='complete($event)'>
    <e-columns>
    . . .
    </e-columns>
</ejs-grid>
`,

})
export class NormalEditComponent implements OnInit {
        
    ngOnInit(): void {
        . . .
    }
    complete(e: any): void {
        // adds the form at bottom
        if (e.requestType === 'add') {
            e.row.parentElement.appendChild(e.row);
        }
       if (e.requestType === 'save') {
          this.grid.selectRow(this.grid.currentViewData.length - 1)   // selects the newly added row
           
        }
    }
    begin(e: any): void {
        if (e.requestType === 'save') {
            e.index = (this.grid.pageSettings.currentPage * this.grid.pageSettings.pageSize) - 1;    // saves the new row in bottom
        }
    }
}
`

Documentation : https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#actionbegin 
                               https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#actioncomplete 
                               https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#selectrow 

Sample               : https://stackblitz.com/edit/angular-kcskdw-qvpwsr?file=normal-edit.html 

Please let us know if you have any further assistance on this.

Regards,
Venkatesh Ayothiraman.

**Comment by susandotmark** [comment]
what about adding record at the bottom in batch mode

**Comment by Madhust** [comment]
@susandotmark We have added the support to add new row form at the bottom of the grid. Please upgrade to the latest version v16.4.44 to use this feature.

Sample: https://stackblitz.com/edit/grid-batch-add-bottom?file=batch-editing.component.ts

Regards,
Madhu Sudhanan P
