### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by susandotmark** [syncfusion/ej2-ng-grids#17]
What are the keyboard shortcuts to add and edit

**Comment by Madhust** [comment]
@susandotmark Please use the `insert` and `F2` keys to add and edit records respectively.

**Comment by susandotmark** [comment]
@Madhust hey, thanks a lot bro. Also, do we have list of these keyboard shortcuts for grid, would you share some links if there are any

**Comment by Madhust** [comment]
@susandotmark Thanks for the update. Please refer to the below help link for available key options. 

https://ej2.syncfusion.com/angular/documentation/grid/accessibility.html#keyboard-navigation

Also the insert and F2 are missed in the key list, we will make the changes to include the missed keys in our documentation.

**Comment by susandotmark** [comment]
@Madhust Thankyou again but isn't there shortcut for updating the changes when its in batch mode?

**Comment by susandotmark** [comment]
> @susandotmark Thanks for the update. Please refer to the below help link for available key options.
> 
> https://ej2.syncfusion.com/angular/documentation/grid/accessibility.html#keyboard-navigation
> 
> Also the insert and F2 are missed in the key list, we will make the changes to include the missed keys in our documentation.

Also,can we add new row on enter key press, that would be great for my requirement

**Comment by jvhariharan** [comment]
Hi Susan,

By default the following key initiate editing/add operation as follows:

•	Insert   –  add a new records
•	F2         –  edit a selected record
•	Delete  -  Delete a selected record
•	Enter    -  Save the edited record


Yes we can add new row while pressing Enter-Key by using ‘key-pressed’ event and ‘addRecord’ method. Please find the code example and sample for your reference.

`let grid: Grid = new Grid(
        {
            dataSource: orderDataSource,
            editSettings: { allowEditing: true, allowAdding: true, allowDeleting: true, mode: 'Normal' },
           . . .
            dataBound: dataBound,
            columns: [
                {
                    field: 'OrderID', isPrimaryKey: true, headerText: 'Order ID', textAlign: 'Right',
                    validationRules: { required: true }, width: 120
                },
               . . .
                }],
        });
    grid.appendTo('#Grid');

    function keypressFun(e: any): void {
        // grid add new row while press on enter key pressed
        if (e.keyCode === 13) {
            this.grid.addRecord()
        }

    function dataBound(args: any) {
        (this.grid as any).on('key-pressed', keypressFun, this)

    }
`

Documentation :

https://ej2.syncfusion.com/documentation/grid/api-grid.html?lang=typescript#databound 
https://ej2.syncfusion.com/documentation/grid/api-grid.html?lang=typescript#addrecord


Regards,
Hariharan

**Comment by susandotmark** [comment]
Thankyou again @jvhariharan, Also, do we have keyboard shortcut for update in batch mode?

**Comment by Madhust** [comment]
@susandotmark You can use the `batchSave` method to update grid in the batch mode.

```
function keypressFun(e: any): void {
    // grid add new row while press on enter key pressed
    if (e.keyCode === 13) {
        this.grid.editModule.batchSave();
    }

function dataBound(args: any) {
    (this.grid as any).on('key-pressed', keypressFun, this)

}
```
https://ej2.syncfusion.com/javascript/documentation/api/grid/edit/#batchsave
