### ISSUE TITLE
Add new row on enter key press

### ISSUE THREAD

**Issue by susandotmark** [syncfusion/ej2-ng-grids#18]
Can we add new row on enter key press from last column of the selected row

**Comment by jvhariharan** [comment]
Hi Susan,
 
Thanks for contacting Syncfusion support.

Yes we can add new row while pressing Enter-Key by using ‘key-pressed’ event and ‘addRecord’ method. Please find the code example and sample for your reference.


`
<ejs-grid #grid [dataSource]='data' (dataBound)='dataBound($event)' allowPaging='true' [pageSettings]='pageSettings' [editSettings]='editSettings' [toolbar]='toolbar'>
    <e-columns>
        <e-column field='OrderID' headerText='Order ID' width='120' textAlign='Right' isPrimaryKey='true' [validationRules]='orderidrules'></e-column>
        . . .
    </e-columns>
</ejs-grid>


[app.component.ts]

. . .
export class NormalEditComponent implements OnInit {
  public data: Object[];
. . .
    @ViewChild('grid')
    public grid = Grid;
    dataBound(args:any){
      (this.grid as any).on('key-pressed', keypressFun, this)
    }
    public ngOnInit(): void {
        this.data = orderDatas;
       . . .
    }
}
function keypressFun(e: any):void{
  // grid add new row while press on enter key pressed
  if(e.keyCode === 13 ){
    this.grid.addRecord()
  }
}
`

Sample:  https://stackblitz.com/edit/angular-jqk4gg-swxnc6?file=normal-edit.component.ts 

Documentation :

https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#addrecord 
https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#databound 

Regards,
Hariharan

**Comment by susandotmark** [comment]
thankyou so much @jvhariharan
