### ISSUE TITLE
new row position

### ISSUE THREAD

**Issue by susandotmark** [syncfusion/ej2-ng-grids#21]
how to define row position to bottom/ add new row to bottom

**Comment by ej2gridsamples** [comment]
Hi Susan,

Thanks for using Syncfusion products.

We can add the newly added record in the bottom position by setting the ‘args.index’ value in the actionBegin event with ‘save’ requestType. We can also add the adding form in the bottom position by using the ‘actionComplete’ event. We have prepared a simple sample based on your requirement. Please refer to the below code example, Documentation link and sample link. 

[component.ts] 
`@Component({ 
    selector: 'control-content', 
    template: `<ejs-grid #grid [dataSource]='data' [pageSettings]='page' allowPaging=true[editSettings]='editSettings' [toolbar]='toolbar' (actionBegin)='begin($event)'(actionComplete)='complete($event)'> 
    <e-columns> 
    . . . 
    </e-columns> 
</ejs-grid> 
`, 
 
}) 
export class NormalEditComponent implements OnInit { 
         
    ngOnInit(): void { 
        . . . 
    } 
    complete(e: any): void { 
        // adds the form at bottom 
        if (e.requestType === 'add') { 
            e.row.parentElement.appendChild(e.row); 
        } 
       if (e.requestType === 'save') { 
          this.grid.selectRow(this.grid.currentViewData.length - 1)   // selects the newly added row 
            
        } 
    } 
    begin(e: any): void { 
        if (e.requestType === 'save') { 
            e.index = (this.grid.pageSettings.currentPage * this.grid.pageSettings.pageSize) - 1;    // saves the new row in bottom 
        } 
    } 
} 
`
Documentation : https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#actionbegin  
                               https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#actioncomplete  
                               https://ej2.syncfusion.com/angular/documentation/grid/api-gridComponent.html#selectrow  

Sample               : https://stackblitz.com/edit/angular-kcskdw-qvpwsr?file=normal-edit.html  

Please let us know if you have any further assistance on this.

Regards, 
Venkatesh A.
