### ISSUE TITLE
Usage of ejs-grid component leads to memory leak

### ISSUE THREAD

**Issue by egozavr** [syncfusion/ej2-ng-grids#22]
## There is a leaky bug

Here is example: https://stackblitz.com/edit/angular-ejs-grid-memleak

Clicking on button toggles `HelloComponent` init/destroy (which may be seen in devtools console). `HelloComponent` template includes `ejs-grid`:
```html
<h2>Grid here</h2>
<ejs-grid></ejs-grid>
```

Number on button (count of `HelloComponent` initializations) is the same as number of class instances in heap snapshot (garbage was preliminarily collected):

![image](https://user-images.githubusercontent.com/2705355/56510481-968b6a00-6532-11e9-864f-62dbce8f3a24.png)

**Comment by egozavr** [comment]
Move to the newer repo: https://github.com/syncfusion/ej2-angular-ui-components/issues/21

**Comment by thavasianand** [comment]
Hi egozavr,

We have checked your given stackblitz link but we are not able to get the memory leak issue. We have measured the memory leak issue using the below general link documentation.

Link: https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots#comparison_view

Snaps shot after the component render.

 

Snap shot for comparison.

 

So, please check this in your end and provide some more detail on this.

Regards,
Thavasianand S.

**Comment by egozavr** [comment]
Answered here:
https://github.com/syncfusion/ej2-angular-ui-components/issues/21

пт, 26 апр. 2019 г. в 17:29, thavasianand <notifications@github.com>:
