### ISSUE TITLE
JIT fails to find `datasource` in ej-grid

### ISSUE THREAD

**Issue by lamLeX** [syncfusion/ej2-ng-grids#4]
I followed this tutorial http://ej2.syncfusion.com/angular/documentation/grid/getting-started.html 

How ever when I run my project, the JIT encounter this error [![Browser error][1]][1]

The InteliSense also show the same error [![IntelliSense error][2]][2]

I set up the `SyncFusionModule` as Angular Module to export all "Syncfusion EJ 2 for Angular" components I'm planning to use in the `BenchmarkModule`. The `GridComponent` in 
`@syncfusion/ej2-ng-grids/src/grid/index` can be picked up by Angular; therefore, it is recognized as an Angular component. However, the `datasouce` is not declared in 'GridComponent' but in its parent `Grid` which is not Angular component but a standard one declared in `@syncfusion\ej2-grids`. It seems like I missed an dependencies import somewhere to help Angular find the definition for `Grid`. But I wasn't sure how to resolve this issue. 

At first, I thought it's due to the fact that I skipped the SystemJS mapping which described in http://ej2.syncfusion.com/angular/documentation/grid/getting-started.html#configuring-system-js; therefore, I raised this question https://stackoverflow.com/questions/45579779/webpack-solution-for-systemjs-mapping. But one of the answers suggested me it may not the reason. 

Here is the GitHub repo https://github.com/lamLeX/IocPerformance/tree/gh-pages/IocPerformanceResultWebApp/src/app in case one would like to know how the files are structured to help me with the dependencies resolving because I don't have much experience in JS dependencies resolving; especially ES6 modules resolve.

This was first asked in this SO https://stackoverflow.com/questions/45625642/dependencies-solving-for-gridcomponent-in-syncfusion-ej2-ng-grids

  [1]: https://i.stack.imgur.com/GtgiR.png
  [2]: https://i.stack.imgur.com/4NKke.png

**Comment by lamLeX** [comment]
Turn out, it's about the case-sensitive issue in html binding.
The `datasource` in  the template should be `dataSource`. 

I would like to change the SyncFusion document example to address this issue. However,
I don't know where to raise this issue to the document repo. Can someone in charge help me raise to issue and close this issue?

Thanks

**Comment by bharathm03** [comment]
@lamLeX thank you for trying ej2-ng-grids. I have checked the document, all the code snippets has correct casing. I believe that grid's data source file got you mistaken the snippet

![image](https://user-images.githubusercontent.com/2254476/29238271-4fdf0032-7f4f-11e7-87d7-9ed086e3d7fa.png)

We will correct the file names to avoid misunderstanding.

Thanks

**Comment by lamLeX** [comment]
@bharathm03 thank you for getting back to me, 
Actually, the document need correcting is http://ej2.syncfusion.com/angular/demos/#/grid/grouping.
I got the code from the html template `grouping.html` to try out and it took me a couple days to figure out what went wrong. Fixing that document should save others from trouble in the future.
Thanks,

**Comment by bharathm03** [comment]
Thanks @lamLeX we will fix the code snippet in demo samples also.

**Comment by bharathm03** [comment]
@lamLeX casing are corrected in snippets of our demo samples. Thanks
