### ISSUE TITLE
RecordDoubleClickEventArgs

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-grids#5]
Hi,

where we can found the "RecordDoubleClickEventArgs" event for the row ?

Regards

j.nord

**Comment by pavithra95subramaniam** [comment]
Hi Nord, 

Essential JS2 Grid doesn’t have in-built record double click event. However you can achieve your requirement by using native angular “dblclick” event. Please refer to the following code example and sample link.

Template: 
```
<ej-grid #grid [dataSource]='data' allowPaging='true' (dblclick)='recordDoubleClick($event)'> // you can use dblclick event  
. . . 
</ej-grid> 
```
Component.ts 
```
export class SelectionComponent implements OnInit { 
    . . . 
    @ViewChild('grid') public grid; 
     
    recordDoubleClick(e: MouseEvent) {  
        let cell: HTMLTableCellElement = <HTMLTableCellElement>(e.target);       
        let column = this.grid.columns[cell.cellIndex];        // to get the column of the double clicked cell
        let row = cell.parentElement.rowIndex; 
        let data= this.grid.getCurrentViewRecords()[row]; //to get the row data of the double clicked cell
}    
} 
```
Sample Link: http://plnkr.co/edit/knf399hw65YkQnesqiFq?p=preview  

Regards,
Pavithra S.

**Comment by j-nord** [comment]
Hi Pavithra,

your example doesn't work.

let row = cell.parentElement.rowIndex;

(TS) Property 'rowIndex' does not exist on type 'HTMLElement'.

Regards
j.nord

**Comment by hariharanjv** [comment]
Hi Nord,

We have modified the above plunker sample to resolve the (TS) issue, and please refer the updated sample link.

Note: `rowIndex` property available on `HTMLTableRowElement`.

Sample link: http://plnkr.co/edit/8SDkAzF1lC8mW2mzbFe8?p=preview  

Regards,
Hariharan
