### ISSUE TITLE
datasoure in grid custom control doesn't work correct

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-grids#7]
we have the grid in a custom control:

In the custom control we have defined the dataSource (ts):

@input() mySource: any;

In the html (ej-grid):
[dataSource]="mySource"

then we can in the application mask define (html):
[mySource]="customerdata"

in the application source we get the data:

this.dataService
	.get("customer")
	.then((res: customerModel[]) => {
		this.customerdata= res;
	})

the problem:
We must call the service 2 times.  Only with 2 times call the data are displayed.
We call the grid refresh method, but everything does not help.

**Comment by RamdhasUeikattan** [comment]
Hi Nord,
 
Thanks for contacting syncfusion Supports.
 
We have analyzed the reported problem and we were unable to reproduce at our end. We have created a GitHub sample that can be downloaded from the below link.
 
Git Sample link: https://github.com/RamdhasUeikattan/ChildCompDataBind 
 
To run the sample, please use the below commands.
 
•	npm install
•	npm start
 
In the above sample, we have done the following things,
 
1.	Created two components “AppComponent” and “GridComponent”.
2.	Placed Grid in ‘’GridComponent” and a search box to find CustomerID in ‘’AppComponent”
3.	Searching will be done and the resultant data is assigned to the parent component property as follows.

`. . .

onClick(): void {
        this.dataService.get('Orders', 'CustomerID', this.filterValue).subscribe(result => {
                   this.orderData = result.d;
        });
    }

. . .
`

Please check the above sample and also provide more information regarding your problem which will help us to analyze further and provide the solution as earlier as possible.
 
Regards,
Ramdhas  Ueikattan

**Comment by j-nord** [comment]
Hi Ramdhas,

we have found the problem. It is not the datasource property, it is the column property:

In the custom control we have:

In the html (ej-grid):
 [dataSource]="myColumns"

the columns "myColumns" was defined in typescript
then we must call the service 2 times. 

When we changed to html-code:

`<e-columns>
	<e-column field='CustomerID' headerText='Customer ID' width=150 ></e-column>
	<e-column field='Freight' headerText='Freight' [format]='form' textAlign='right' width=150></e-column>
	<e-column field='ShipCity' headerText='Ship City' width=150></e-column>
	<e-column field='ShipName' headerText='Ship Name' width=150></e-column>
</e-columns>
`

then it works.


Regards

j.nord

**Comment by RamdhasUeikattan** [comment]
Hi Nord,

As you said, we have changed the code to use columns from the Component class instead of declaring it in the template and it worked fine at our end.

https://github.com/RamdhasUeikattan/ChildCompDataBind/blob/master/app/grid.component.ts#L20

```
template: ` <ej-grid #grid [locale]='de-DE' [dataSource]='mySource' [columns]='columns'>
                </ej-grid> `
 . . .

  ngOnInit(){
   this.columns = <Column[]> [
   { field: 'OrderID', headerText: 'Order   ID', textAlign: 'right', width: 120, type: 'number' },
   { field: 'CustomerID', width: 140, headerText: 'Customer   ID', type: 'string' },
   { field: 'Freight', headerText: 'Freight', textAlign: 'right', width: 120, format: 'C2' },
   { field: 'ShipCountry', headerText: 'Ship   Country', width: 140 }
   ];
   }   

. . .
    

```

We have also updated the sample by using columns from the component class. Please check the below sample and share more information like Component class etc. to check this at our end and provide solution as early as possible. 

Sample: https://github.com/RamdhasUeikattan/ChildCompDataBind

Regards,
Ramdhas  Ueikattan

**Comment by j-nord** [comment]
Hi Ramdhas,

thanks for the answer, but that is not realistic.

In the custom Control we have:
`
@Input()
set columns(value: gridColumn[]) {
	this._columns = <Column[]>value;
}
`

And in the application you define the fields:
[myColumns]='columns'      <- HTML

columns: ColumnModel[] =    <- 

So you can define the columns for each masks (customers, products, ...)

And then we have the Problem that we must call the servie two times.

Regards

j.nord

**Comment by RamdhasUeikattan** [comment]
Hi Nord,

Thanks for the update.

From your given information, we are unable to reproduce the reported problem. We have changed the github sample from your requirement as we suspect. Please refer the below github sample.

Sample link: https://github.com/RamdhasUeikattan/ChildCompDataBind 

In the above sample, we have changed the column collection dynamically and bounded it to the child component(in which Grid component present).

https://github.com/RamdhasUeikattan/ChildCompDataBind/commit/aa8cedb486f81a191a49c19c945877d42bf44aff#diff-808b7233b8d9350da9fe1d2eb2e2d9d8R19

In the sample, you can change the grid columns and data source dynamically by selecting the dropdown value.

Please share the following information to find out the problem and provide the solution early as possible.

1.	Are you constructing the column collection dynamically, if so please how it has been constructed and how it was assigned to the myColumns property?
2.	Please share the screenshot of the problem.
3.	If possible please share the truncated column setting and data source assigning the code.
4.	If possible please update the above GitHub sample to replicate your problem and send to us.

Regards,
Ramdhas  Ueikattan

**Comment by j-nord** [comment]
Hi Ramdhas,

Your example is how we have that too. With one exception: we have a promise result.

In one query, it works well, not in the next, and in the next with a workaround (timeout). So you just can not use the grid.

Everything works fine under Javascript 1. Under Javascript 2, we only have problems.

Regards

j. nord

**Comment by RamdhasUeikattan** [comment]
Hi Nord,

Sorry for the inconvenience caused. We are unable to proceed further with the given information. Could you please provide the details which are requested in [our last update](https://github.com/syncfusion/ej2-ng-grids/issues/7#issuecomment-345233320) else we request you to create a support incident for this problem using the below link. 

https://www.syncfusion.com/Account/Logon?ReturnUrl=/support/directtrac

Please let us know if you have any concerns.

Regards,
Ramdhas  Ueikattan

**Comment by j-nord** [comment]
Hi Ramdhas,
we have found the problem in the grid:

When you have a wrong format definition in the column, you get not an error message.

**The only symptom:**
you must call the service 2 times. and then the data are displayed. So you can search the error one or two days.

Regards
j.nord
