### ISSUE TITLE
localization 'de' null date -> 01.01.1970

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-grids#8]
Hi,

we have german format 'de'  format: 'yMMdd' in the column. When we have a null value in the date field, in the grid column in the grid is displayed  '01.01.1970'. This ist wrong. The column must display a empty field.

Regards

j.nord

**Comment by pavithra95subramaniam** [comment]
Hi Nord,

We have analyzed your query and we have considered “Null value shows a date in date column” as a defect and logged a report for the same. This fix will be available in our November 30, 2017 release.

Regards,
Pavithra S.

**Comment by j-nord** [comment]
Hi Pavithra,

it works fine.

Regards
j.nord

**Comment by LastCodeDE** [comment]
Hi Pavithra,

we are using this method currently in version 16.1.28.

Unfortunately we noted a new failure with the null value in the date column.

If the first row in the column contains a null value in the date column then the value of the next rows will be false displayed (See Attachment).

![firstrowcontainsdate](https://user-images.githubusercontent.com/15675686/37760916-6dc0cff0-2db8-11e8-8b70-2f278f4a7064.png)
First row contains a normal date.

![firstrownull](https://user-images.githubusercontent.com/15675686/37760937-7d816df0-2db8-11e8-8b66-fdfe21aa50bc.png)
First row contains a null value in date column

Column format is: 'yMMdd'.

Regards
LastCodeDE
